name: Test LunarDate
run-name: ${{ github.actor }} tests LunarDate
on: [pull_request]
jobs:
  test-modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - run: npm install
      - run: npm run test
